### ISSUE TITLE
[CT-1519] [Bug] Better error message for misspecified dist key yaml config

### ISSUE THREAD

**Issue by dluftspring** [dbt-labs/dbt-redshift#224]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If you set the dist key in a `model.yml` file like

```yaml
version: 2
models:
  - name: a_real_table
    config:
      sort:
        - primary_key
        - foreign_key
      dist:
        - primary_key
```

dbt will throw the following error

`list has no attribute strip`

Which is generic and non descriptive of what the user should fix. The issue is that since dist keys can only be single valud properties it should be specified as `dist: primary_key`.

### Expected Behavior

A better message that isn't exposing the underlying python machinery and indicates what the user should do to fix the issue e.g. Single valued properties cannot be specified as a list

### Steps To Reproduce

See Current Behaviour. If you set up a model like that in any dbt project you will reproduce the error

### Environment

```markdown
- OS: Mac
- Python: 3.9
- dbt-core:
- dbt-redshift: 1.3.0
```
