### ISSUE TITLE
[ADAP-474] [Feature] Accept users, groups, or roles in grants config on resource

### ISSUE THREAD

**Issue by stevenayers-tvx** [dbt-labs/dbt-redshift#415]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After specifically creating the group `finance_department` in Redshift, I cannot use it as a grantee in the grant config.

I can see the group when I run `SELECT * FROM pg_group`

```yaml
models:
  - name: specific_model
    config:
      grants:
        select: ['finance_department']
```

Error: `user "finance_department" does not exist`

### Expected Behavior

Grantee syntax says groups, not just users, should be accepted: https://docs.getdbt.com/reference/resource-configs/grants#common-syntax

### Steps To Reproduce

1. Create a group in redshift
2. Add to a grants config on a model

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```

**Comment by dbeatty10** [comment]
Thanks for following up @stevenayers-tvx !

Only granting to (and revoking from) Redshift _users_ was explicitly covered in the original implementation of grants in https://github.com/dbt-labs/dbt-redshift/pull/131  -- granting/revoking for Redshift _groups_ and _roles_ was not.

This deserves clarification in the docs, and I've opened https://github.com/dbt-labs/docs.getdbt.com/pull/3245 accordingly.

I'm going to convert this into a feature request to add support for grants for Redshift groups and roles.

**Comment by amardatar** [comment]
We use this extensively, and intentional or not it seems that just using `group <group_name>` works perfectly fine. @stevenayers-tvx does it work if you just do this?

```
models:
  - name: specific_model
    config:
      grants:
        select: ['group finance_department']
```
