### ISSUE TITLE
[ADAP-573] [Feature] create a target-centric workflow to support autocommit-dependent workflows

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/dbt-redshift#463]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The redshift connector that underlies this adapter does not have the same transaction semantics as the Postgres connector. Users who want to run certain macros inside of their DBT project are blocked by this changed semantics. 

We want to unblock those users (#425 ). One way that we can do so is letting them to specify autocommit for all connections in their profile config.

For example,

```
profile-to-my-RS-target:
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      [autocommit: False]

profile-to-my-RS-target-with-autocommit-enabled:
  target: dev
  outputs:
    dev:
      type: redshift
      ...
      autocommit: True
```
Users condense specify the autocommit profile with the `--profile` flag on the CLI and in Cloud.

Because autocommit is not something that preserves ACID properties, etc., we need to ensure that the we educate users proper use of this mechanism. 

A docs issue PR exists at https://github.com/dbt-labs/docs.getdbt.com/issues/3401

### Who will this benefit?

Redshift users who want to have macros with CREATE DATABASE, VACUUM, and similar.

### Are you interested in contributing this feature?

Yep!
