### ISSUE TITLE
[ADAP-634] [Bug] Redshift fails to run several threads

### ISSUE THREAD

**Issue by sphinks** [dbt-labs/dbt-redshift#501]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have found several issues about performance degradation while using RA3 node. However, I'm expecting failure of dbt run if I switch from 1 thread to several.

My DBT profile:
```
    dev:
      type: redshift
      host: redshift-host

      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      dbname: dev
      schema:  dev
      threads: 4
      ra3_node: true
```
The error I get:
```
18:08:46    could not open relation with OID 615797
```
That happens not at the same model, sometimes the first model could fail. Other time it could be model at the end of list.
What helps a little bit - setup `connect_timeout: 999999`. I have found that solution at some bug. It still fails, but happens not at the very begining.

What I'm using:
Redshift RA3 cluster
DBT - 1.3.2
dbt-redshift - 1.3.0

I try to switch to the latest version of dbt (1.5.1) and dbt-redshift (1.5.5), not luck, but the error message became ' The read operation timed out'.

### Expected Behavior

DBT runs in parallel with out any issues.

### Steps To Reproduce

1. Setup dbt project.
2. Start with specified DBT profile and 1 thread.
3.  Switch to several threads and rerun project.

### Environment

```markdown
- OS:Windows Server 2016 (the same issue happens with remote dbt running on Linux OS)
- Python:Python 3.9.13
- dbt-core: 1.3.2
- dbt-redshift: 1.3.0
```
