### ISSUE TITLE
[Bug] Pinning to `dbt-redshift~=1.8` installs dbt-core 1.9.0-b2

### ISSUE THREAD

**Issue by ilmari-aalto** [dbt-labs/dbt-redshift#930]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running `pip install --upgrade dbt-redshift~=1.8` the beta version 1.9.0-b2 of dbt-core is installed. I'd expect the last stable version 1.8.* of dbt-core to be installed instead.

After running the intallation, `dbt --version` output is the following:

```
dbt --version
Core:
  - installed: 1.9.0-b2
  - latest:    1.8.7    - Ahead of latest version!

Plugins:
  - redshift: 1.8.1 - Not compatible!
  - postgres: 1.8.2 - Not compatible!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Expected Behavior

I'd expect the latest stable version of `dbt-core` to be installed instead of the beta version. At the moment of writing, this would be the version `1.8.7` of `dbt-core`.

### Steps To Reproduce

1. In Mac, with `pip 24.2`
2. Running `pip install --upgrade dbt-redshift~=1.8` from a clean slate (no previous dbt installation in the virtual env)
3. The beta version of `dbt-core` is installed, as shown by running the command `dbt --version` after the step 2.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```
